### ISSUE TITLE
Error: no Bels remaining of type '$scopeinfo'

### ISSUE THREAD

**Issue by janrinze** [openXC7/nextpnr-xilinx#67]
To keep thing simple I have the example at [no_bels_scopeinfo](https://github.com/janrinze/Xilinx_Tests/tree/main/no_bels_scopeinfo)

The example is a cut down from a video output test.

**Comment by janrinze** [comment]
fix is available at yosyshq : https://github.com/YosysHQ/nextpnr/commit/d00fdc8f7a20fe0e34911bb0cecb42a876738712

**Comment by gHashTag** [comment]
**This no longer reproduces on `stable-backports`.** I ran your `no_bels_scopeinfo` case end to end and it builds.

```
$ yosys -p "read_verilog test.v; synth_xilinx -flatten -family xc7 -top top; write_json t.json"
$ grep -c scopeinfo t.json
2
$ nextpnr-xilinx --chipdb xc7a200t.bin --xdc test.xdc --json t.json --fasm t.fasm
$ ls -lh t.fasm
108K
```

No error, and the FASM is produced. The `$scopeinfo` cells are still present in the JSON, so the input is the same as when you filed it — what changed is that they are now skipped on import:

`frontend/frontend_base.h:448`, in `import_leaf_cell`:

```cpp
auto cell_type = impl.get_cell_type(cd);
if (cell_type == "$scopeinfo")
    return;
```

Environment: `nextpnr-xilinx 0.9.2-44-ga70ae4a8` (branch `stable-backports`), built from source on macOS arm64 with `-DUSE_OPENMP=OFF`; chipdb generated for `xc7a200tfbg484-2` from `prjxray-db` artix7; yosys 0.59.

I did not bisect to find which commit introduced the guard, so I can't say which release first carried it — only that current `stable-backports` handles it. Probably closable.

**Comment by hansfbaier** [comment]
@gHashTag Awesome, thanks!
